# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.26.4/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.26.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/hp12384/Library/Mobile Documents/com~apple~CloudDocs/Documents/LeapSDK/samples"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/hp12384/Library/Mobile Documents/com~apple~CloudDocs/Documents/LeapSDK/samples"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.26.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.26.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/hp12384/Library/Mobile Documents/com~apple~CloudDocs/Documents/LeapSDK/samples/CMakeFiles" "/Users/hp12384/Library/Mobile Documents/com~apple~CloudDocs/Documents/LeapSDK/samples//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/hp12384/Library/Mobile Documents/com~apple~CloudDocs/Documents/LeapSDK/samples/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named leapc_example

# Build rule for target.
leapc_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 leapc_example
.PHONY : leapc_example

# fast build rule for target.
leapc_example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leapc_example.dir/build.make CMakeFiles/leapc_example.dir/build
.PHONY : leapc_example/fast

#=============================================================================
# Target rules for targets named libExampleConnection

# Build rule for target.
libExampleConnection: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libExampleConnection
.PHONY : libExampleConnection

# fast build rule for target.
libExampleConnection/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libExampleConnection.dir/build.make CMakeFiles/libExampleConnection.dir/build
.PHONY : libExampleConnection/fast

#=============================================================================
# Target rules for targets named CallbackSample

# Build rule for target.
CallbackSample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CallbackSample
.PHONY : CallbackSample

# fast build rule for target.
CallbackSample/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CallbackSample.dir/build.make CMakeFiles/CallbackSample.dir/build
.PHONY : CallbackSample/fast

#=============================================================================
# Target rules for targets named ImageSample

# Build rule for target.
ImageSample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ImageSample
.PHONY : ImageSample

# fast build rule for target.
ImageSample/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageSample.dir/build.make CMakeFiles/ImageSample.dir/build
.PHONY : ImageSample/fast

#=============================================================================
# Target rules for targets named PollingSample

# Build rule for target.
PollingSample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PollingSample
.PHONY : PollingSample

# fast build rule for target.
PollingSample/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PollingSample.dir/build.make CMakeFiles/PollingSample.dir/build
.PHONY : PollingSample/fast

#=============================================================================
# Target rules for targets named InterpolationSample

# Build rule for target.
InterpolationSample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 InterpolationSample
.PHONY : InterpolationSample

# fast build rule for target.
InterpolationSample/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InterpolationSample.dir/build.make CMakeFiles/InterpolationSample.dir/build
.PHONY : InterpolationSample/fast

#=============================================================================
# Target rules for targets named MultiDeviceSample

# Build rule for target.
MultiDeviceSample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MultiDeviceSample
.PHONY : MultiDeviceSample

# fast build rule for target.
MultiDeviceSample/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultiDeviceSample.dir/build.make CMakeFiles/MultiDeviceSample.dir/build
.PHONY : MultiDeviceSample/fast

CallbackSample.o: CallbackSample.c.o
.PHONY : CallbackSample.o

# target to build an object file
CallbackSample.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CallbackSample.dir/build.make CMakeFiles/CallbackSample.dir/CallbackSample.c.o
.PHONY : CallbackSample.c.o

CallbackSample.i: CallbackSample.c.i
.PHONY : CallbackSample.i

# target to preprocess a source file
CallbackSample.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CallbackSample.dir/build.make CMakeFiles/CallbackSample.dir/CallbackSample.c.i
.PHONY : CallbackSample.c.i

CallbackSample.s: CallbackSample.c.s
.PHONY : CallbackSample.s

# target to generate assembly for a file
CallbackSample.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CallbackSample.dir/build.make CMakeFiles/CallbackSample.dir/CallbackSample.c.s
.PHONY : CallbackSample.c.s

ExampleConnection.o: ExampleConnection.c.o
.PHONY : ExampleConnection.o

# target to build an object file
ExampleConnection.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libExampleConnection.dir/build.make CMakeFiles/libExampleConnection.dir/ExampleConnection.c.o
.PHONY : ExampleConnection.c.o

ExampleConnection.i: ExampleConnection.c.i
.PHONY : ExampleConnection.i

# target to preprocess a source file
ExampleConnection.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libExampleConnection.dir/build.make CMakeFiles/libExampleConnection.dir/ExampleConnection.c.i
.PHONY : ExampleConnection.c.i

ExampleConnection.s: ExampleConnection.c.s
.PHONY : ExampleConnection.s

# target to generate assembly for a file
ExampleConnection.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libExampleConnection.dir/build.make CMakeFiles/libExampleConnection.dir/ExampleConnection.c.s
.PHONY : ExampleConnection.c.s

ImageSample.o: ImageSample.c.o
.PHONY : ImageSample.o

# target to build an object file
ImageSample.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageSample.dir/build.make CMakeFiles/ImageSample.dir/ImageSample.c.o
.PHONY : ImageSample.c.o

ImageSample.i: ImageSample.c.i
.PHONY : ImageSample.i

# target to preprocess a source file
ImageSample.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageSample.dir/build.make CMakeFiles/ImageSample.dir/ImageSample.c.i
.PHONY : ImageSample.c.i

ImageSample.s: ImageSample.c.s
.PHONY : ImageSample.s

# target to generate assembly for a file
ImageSample.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ImageSample.dir/build.make CMakeFiles/ImageSample.dir/ImageSample.c.s
.PHONY : ImageSample.c.s

InterpolationSample.o: InterpolationSample.c.o
.PHONY : InterpolationSample.o

# target to build an object file
InterpolationSample.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InterpolationSample.dir/build.make CMakeFiles/InterpolationSample.dir/InterpolationSample.c.o
.PHONY : InterpolationSample.c.o

InterpolationSample.i: InterpolationSample.c.i
.PHONY : InterpolationSample.i

# target to preprocess a source file
InterpolationSample.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InterpolationSample.dir/build.make CMakeFiles/InterpolationSample.dir/InterpolationSample.c.i
.PHONY : InterpolationSample.c.i

InterpolationSample.s: InterpolationSample.c.s
.PHONY : InterpolationSample.s

# target to generate assembly for a file
InterpolationSample.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InterpolationSample.dir/build.make CMakeFiles/InterpolationSample.dir/InterpolationSample.c.s
.PHONY : InterpolationSample.c.s

MultiDeviceSample.o: MultiDeviceSample.c.o
.PHONY : MultiDeviceSample.o

# target to build an object file
MultiDeviceSample.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultiDeviceSample.dir/build.make CMakeFiles/MultiDeviceSample.dir/MultiDeviceSample.c.o
.PHONY : MultiDeviceSample.c.o

MultiDeviceSample.i: MultiDeviceSample.c.i
.PHONY : MultiDeviceSample.i

# target to preprocess a source file
MultiDeviceSample.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultiDeviceSample.dir/build.make CMakeFiles/MultiDeviceSample.dir/MultiDeviceSample.c.i
.PHONY : MultiDeviceSample.c.i

MultiDeviceSample.s: MultiDeviceSample.c.s
.PHONY : MultiDeviceSample.s

# target to generate assembly for a file
MultiDeviceSample.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MultiDeviceSample.dir/build.make CMakeFiles/MultiDeviceSample.dir/MultiDeviceSample.c.s
.PHONY : MultiDeviceSample.c.s

PollingSample.o: PollingSample.c.o
.PHONY : PollingSample.o

# target to build an object file
PollingSample.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PollingSample.dir/build.make CMakeFiles/PollingSample.dir/PollingSample.c.o
.PHONY : PollingSample.c.o

PollingSample.i: PollingSample.c.i
.PHONY : PollingSample.i

# target to preprocess a source file
PollingSample.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PollingSample.dir/build.make CMakeFiles/PollingSample.dir/PollingSample.c.i
.PHONY : PollingSample.c.i

PollingSample.s: PollingSample.c.s
.PHONY : PollingSample.s

# target to generate assembly for a file
PollingSample.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PollingSample.dir/build.make CMakeFiles/PollingSample.dir/PollingSample.c.s
.PHONY : PollingSample.c.s

leapc_main.o: leapc_main.c.o
.PHONY : leapc_main.o

# target to build an object file
leapc_main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leapc_example.dir/build.make CMakeFiles/leapc_example.dir/leapc_main.c.o
.PHONY : leapc_main.c.o

leapc_main.i: leapc_main.c.i
.PHONY : leapc_main.i

# target to preprocess a source file
leapc_main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leapc_example.dir/build.make CMakeFiles/leapc_example.dir/leapc_main.c.i
.PHONY : leapc_main.c.i

leapc_main.s: leapc_main.c.s
.PHONY : leapc_main.s

# target to generate assembly for a file
leapc_main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leapc_example.dir/build.make CMakeFiles/leapc_example.dir/leapc_main.c.s
.PHONY : leapc_main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CallbackSample"
	@echo "... ImageSample"
	@echo "... InterpolationSample"
	@echo "... MultiDeviceSample"
	@echo "... PollingSample"
	@echo "... leapc_example"
	@echo "... libExampleConnection"
	@echo "... CallbackSample.o"
	@echo "... CallbackSample.i"
	@echo "... CallbackSample.s"
	@echo "... ExampleConnection.o"
	@echo "... ExampleConnection.i"
	@echo "... ExampleConnection.s"
	@echo "... ImageSample.o"
	@echo "... ImageSample.i"
	@echo "... ImageSample.s"
	@echo "... InterpolationSample.o"
	@echo "... InterpolationSample.i"
	@echo "... InterpolationSample.s"
	@echo "... MultiDeviceSample.o"
	@echo "... MultiDeviceSample.i"
	@echo "... MultiDeviceSample.s"
	@echo "... PollingSample.o"
	@echo "... PollingSample.i"
	@echo "... PollingSample.s"
	@echo "... leapc_main.o"
	@echo "... leapc_main.i"
	@echo "... leapc_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

